### ISSUE TITLE
Discord link is dead

### ISSUE THREAD

**Issue by MrZander** [CentralValleyMesh/centralvalleymesh.github.io#11]
The link to join the discord is dead

> This invite may be expired, or you might not have permission to join.

**Comment by daviesgeek** [comment]
Thanks so much, updating it right now!

**Comment by daviesgeek** [comment]
Should be good now, I updated the invite to never expire and copied the new link. It looks like the UID is the same, so I'm guessing something got reset on my end for the invite link, but I copied over the new link format anyways.
